#' Write DLS Advice to File
#'
#' Write the advisory calculations for a data-limited stock (DLS) to a file.
#'
#' @param x a list generated by the \code{DLS3.2} function.
#' @param file a filename.
#'
#' @seealso
#' \code{\link{readDLS}} reads DLS advisory calculations from a file into a
#' list.
#'
#' \code{\link[icesAdvice]{DLS3.2}} in the \pkg{icesAdvice} package can be used
#' to calculate catch advice for data-limited stocks.
#'
#' \code{\link{icesTAF-package}} gives an overview of the package.
#'
#' @examples
#' \dontrun{
#' library(icesAdvice)
#' survey <- data.frame(year=2001:2010, randu[1:10,])
#' dls <- DLS3.2(1000, survey$y)
#' writeDLS(dls, "dls-output.txt")
#' dls2 <- readDLS("dls-output.txt")
#' }
#' @export

writeDLS <- function(x, file)
{
  nn <- names(x)
  write(nn[1], file)
  write(x[[1]], file, append=TRUE)
  for(i in 2:length(x))
  {
    write("", file, append=TRUE)
    write(nn[i], file, append=TRUE)
    write(x[[i]], file, ncolumns=10, append=TRUE)
  }
  invisible(NULL)
}
